require 'json'
require 'active_support'
require 'active_support/core_ext'

info = JSON.parse(File.read(File.expand_path('../../autoload/serverspec_info.json', __FILE__)))


# @param [String] name
# @param [String] body
def puts_snippet(name, body)
  puts "snippet #{name}"
  puts "options head"
  puts body.indent(2)
  puts
end

puts '# This file is automatically generated by lib/gen_snippet.rb'
puts

# Resources
puts '# Resource snippets'
puts
info.each_key do |res|
  puts_snippet(res, <<-EOC)
describe #{res}('${1:#:NAME}') do
  ${0}
end
  EOC
end


# matchers
puts
puts '# Matcher snippets'
puts
info.each do |res, val|
  puts "# for #{res}"
  val['matchers'].each do |name, info|
    if info['parameters'].present?
      v = info['parameters'].each.with_index.map{|x, i| "${#{i}:#:#{x}}"}.join(", ")
      arg = "(#{v})"
    end

    if info['chains'].present?
      chain = info['chains'].each.with_index(1).map{|x, i| ".#{x}(${#{i}})"}.join
    end
    
    puts_snippet("#{res}_#{name}", <<-EOC)
it { should #{name}#{arg}#{chain} }
    EOC
  end

  val['its_targets'].each do |name|
    puts_snippet("#{res}_#{name[1..-1]}", <<-EOC)
its(#{name}) { should ${1:be} ${0} }
    EOC
  end
end
